### ISSUE TITLE
ALLHiC_prune  

### ISSUE THREAD

**Issue by wyim-pgl** [sc-zhang/ALLHiC_components#1]
Hi @sc-zhang!
I am trying to use ALLHiC_prune. However, it kept generating "Segmentation fault (core dumped)" in "Getting contig pairs" step

I am using below version as environment.
```
gcc | 9.2.0
libgcc_mutex | 0.1
openmp_mutex | 4.5
bzip2 | 1.0.8
c-ares | 1.18.1
ca-certificates | 2021.10.26
htslib | 1.14
krb5 | 1.19.2
libcurl | 7.81.0
libdeflate | 1.9
libedit | 3.1.20210910
libev | 4.33
libgcc-ng | 11.2.0
libgomp | 11.2.0
libnghttp2 | 1.46.0
libssh2 | 1.10.0
libstdcxx-ng | 11.2.0
libzlib | 1.2.11
ncurses | 6.3
openssl | 1.1.1m
tk | 8.6.11
xz | 5.2.5
zlib | 1.2.11
```
![image](https://user-images.githubusercontent.com/907041/150602959-e622eb63-f348-4440-bcbe-23bbfcd33f81.png)

Do you have any idea and recommendations?
Also I found same error from ALLHiC repository.

Thanks
Won

**Comment by sc-zhang** [comment]
It may caused by adding all reads name which need to be removed to an hash table. I modified it these days, and reduced the cost of memory, now the usage of memory just depends on how many contigs here. And you may try the newest version of ALLHiC_prune in the main branch of this repo.
