### ISSUE TITLE
Prune generated an extremely large log file caused my server crash

### ISSUE THREAD

**Issue by hamidashrafi** [sc-zhang/ALLHiC_components#2]
The ALLHiC_Prune program caused my file system to fill out fast and eventually crash it be filling all 1TB space available. I downloaded  new version from the ALLHiC_components website and the size of the file is half of the original not working program. Then it is not clear what needs to be done to it. Ok, you make it executable but after running it it is looking for a couple of missing libraries. Nothing make sense.

**Comment by sc-zhang** [comment]
The library can be found from https://github.com/samtools/htslib, after install it, add the lib path of htslib to your environment variable LD_LIBRARY_PATH, and this program can be run without this error.
