### ISSUE TITLE
ALLHiC_partition.py

### ISSUE THREAD

**Issue by lilyynu** [sc-zhang/ALLHiC_components#3]
Dear  Professor Zhang,
After partition chromosome with ALLHiC_partition.py, I got a fasta file and a bam file for each chromosome, respectively. Although I try the script allhic_extract.sh, optimize.sh, and allhic_build.sh to get the fasta file at chromosome level, the results seems not good.
<img width="882" alt="image" src="https://user-images.githubusercontent.com/111746565/204304292-4de4096f-33da-461e-94a9-5d61ad24ede8.png">
<img width="636" alt="image" src="https://user-images.githubusercontent.com/111746565/204304436-844586c3-b431-4a6c-acfb-1fbe44e149b0.png">
How should I do correctly for the following analysis? Can you provide a script for me?

**Comment by sc-zhang** [comment]
The script ALLHiC_partition.py was an experimental script that is not recommended to use it for assembly, please use the original ALLHiC(https://github.com/tangerzhang/ALLHiC) for these operations.

**Comment by lilyynu** [comment]
Thanks for your fast reply. I am sorry I wrote it wrong. Actually, I used the script partition_gmap.py to partition the chromosome, and I got a fasta file and a bam file for each chromosome, respectively. How should I do next?

**Comment by sc-zhang** [comment]
For drawing heatmap, the bam file must be unpruned one (the original bam which was generated by mapping HiC reads to assembly that not been pruned), because the allhic prune remove a lot of hic signals to make it possible to partition
